version: "3.2"
services:
  postgres_school:
    image: postgres:16.4
    container_name: postgres_school
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: school
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
volumes:
  school_management_data:
